### ISSUE TITLE
Addtional ^M characters on Windows

### ISSUE THREAD

**Issue by jdhao** [dense-analysis/ale#2958]
## Information

**Neovim version**

NVIM v0.5.0-172-g1ff5b60cb
Build type: RelWithDebInfo

Operating System: Windows 10 version 1803

## What went wrong

The ALE lint message on the status line has addtional `^M` character for Windows.

![image](https://user-images.githubusercontent.com/16662357/71887273-b7572680-3178-11ea-8c52-8a86191e0ebe.png)

## Reproducing the bug

minimal `init.vim`:

```vim
set rtp+=C:\Users\Administrator\AppData\Local\nvim-data\plugged\ale

" linters for different filetypes
let g:ale_linters = {
    \ 'python': ['pylint', 'flake8'],
    \ 'vim': ['vint']
\}

" Only run linters in the g:ale_linters dictionary
let g:ale_linters_explicit = 1

" Linter signs
let g:ale_sign_error = '❌'
let g:ale_sign_warning = '!'
```

Open a Python source file with the above `init.vim`:

```
nvim-qt -- -u init.vim test.py
```

You should be able to see that the warnning message on status line
has additional `^M` character.

I believe this is an issue with new line handling from linters on Windows. I
have previously been using Neomake for linting my code and haven't met this
issue.

### :ALEInfo

```
 Current Filetype: python
Available Linters: ['bandit', 'flake8', 'mypy', 'prospector', 'pycodestyle', 'pydocstyle', 'pyflakes', 'pylama', 'pylint', 'pyls', 'pyre', 'vulture']
  Enabled Linters: ['flake8', 'pylint']
 Suggested Fixers: 
  'add_blank_lines_for_python_control_statements' - Add blank lines before control statements.
  'autopep8' - Fix PEP8 issues with autopep8.
  'black' - Fix PEP8 issues with black.
  'isort' - Sort Python imports with isort.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'reorder-python-imports' - Sort Python imports with reorder-python-imports.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'yapf' - Fix Python files with yapf.
 Linter Variables:

let g:ale_python_auto_pipenv = 0
let g:ale_python_flake8_auto_pipenv = 0
let g:ale_python_flake8_change_directory = 1
let g:ale_python_flake8_executable = 'flake8'
let g:ale_python_flake8_options = ''
let g:ale_python_flake8_use_global = 0
let g:ale_python_pylint_auto_pipenv = 0
let g:ale_python_pylint_change_directory = 1
let g:ale_python_pylint_executable = 'pylint'
let g:ale_python_pylint_options = ''
let g:ale_python_pylint_use_global = 0
let g:ale_python_pylint_use_msg_id = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = v:null
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = v:null
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 0
let g:ale_fixers = {}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'vim': ['vint'], 'python': ['pylint', 'flake8']}
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '❌'
let g:ale_sign_info = '!'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '❌'
let g:ale_sign_style_warning = '!'
let g:ale_sign_warning = '!'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) flake8
(finished - exit code 1) 'cmd /s/c "flake8 --version"'

<<<OUTPUT STARTS>>>
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 182, in load_plugin
    self._load(verify_requirements)
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 154, in _load
    self._plugin = resolve()
  File "d:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pycodestyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 412, in run
    self._run(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 399, in _run
    self.initialize(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 381, in initialize
    self.find_plugins()
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 197, in find_plugins
    self.check_plugins.load_plugins()
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 434, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 319, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 432, in load_plugin
    return plugin.load_plugin()
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 189, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.ambiguous_identifier" due to No module named 'pycodestyle'.
<<<OUTPUT ENDS>>>

(executable check - success) pylint
(finished - exit code 4) 'cmd /s/c "cd /d D:\code_exprt && pylint  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n D:\code_exprt\warp_image.py"'

<<<OUTPUT STARTS>>>
************* Module warp_image
warp_image.py:12:4: W0612 (unused-variable) Unused variable 'ret'
warp_image.py:15:4: W0612 (unused-variable) Unused variable 'im2'
warp_image.py:15:19: W0612 (unused-variable) Unused variable 'hierarchy'

------------------------------------------------------------------
Your code has been rated at 9.06/10 (previous run: 9.06/10, +0.00)

<<<OUTPUT ENDS>>>

(finished - exit code 1) 'cmd /s/c "cd /d D:\code_exprt && flake8 --format=default - < C:\Users\ADMINI~1\AppData\Local\Temp\nvimzGqOMA\1\warp_image.py"'

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) 'cmd /s/c "flake8 --version"'

<<<OUTPUT STARTS>>>
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 182, in load_plugin
    self._load(verify_requirements)
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 154, in _load
    self._plugin = resolve()
  File "d:\anaconda\lib\site-packages\pkg_resources\__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'pycodestyle'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\Scripts\flake8.exe\__main__.py", line 9, in <module>
  File "d:\anaconda\lib\site-packages\flake8\main\cli.py", line 16, in main
    app.run(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 412, in run
    self._run(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 399, in _run
    self.initialize(argv)
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 381, in initialize
    self.find_plugins()
  File "d:\anaconda\lib\site-packages\flake8\main\application.py", line 197, in find_plugins
    self.check_plugins.load_plugins()
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 434, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 319, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 432, in load_plugin
    return plugin.load_plugin()
  File "d:\anaconda\lib\site-packages\flake8\plugins\manager.py", line 189, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.ambiguous_identifier" due to No module named 'pycodestyle'.
<<<OUTPUT ENDS>>>

(started) 'cmd /s/c "cd /d D:\code_exprt && pylint  --output-format text --msg-template="{path}:{line}:{column}: {msg_id} ({symbol}) {msg}" --reports n D:\code_exprt\warp_image.py"'
(finished - exit code 1) 'cmd /s/c "cd /d D:\code_exprt && flake8 --format=default - < C:\Users\ADMINI~1\AppData\Local\Temp\nvimzGqOMA\3\warp_image.py"'

<<<NO OUTPUT RETURNED>>>
```

**Comment by w0rp** [comment]
I'm willing to bet this bug exists and is specific to pylint on Windows.

**Comment by jdhao** [comment]
I have also tried `flake8` and the error persists. So this problem is not specific to pylint on Windows. Maybe this has something to do with how output message from various linters is parsed by ALE?

**Comment by w0rp** [comment]
Okay, "I am Jack's complete lack of surprise."

Yeah, it's because Windows has different newline characters and generally sucks. I can fix this without too much effort when I get time to boot up Windows and run the same tools again, or someone else can have a go at it. Even just trimming the message might be enough to fix this kind of thing forever.

**Comment by cpkio** [comment]
I confirm same behaviour with Haskell linting.

**Comment by jgehrig** [comment]
I also see this `^M` behavior with ALE + Windows.

**Comment by jgehrig** [comment]
@w0rp What can I do to get this fixed?

The Pull Request above was closed due to inactivity, but resolves `^M` the issue for me on Windows.

The fix should be trivial, `substitute(l:msg, '\r', '', 'g')` but I may not have chosen the best location. I am happy to clean up the code, address feedback, add tests, and get this ready for merge. Just let me know.

While it is often unpleasant to support Windows, it also has many users. Thanks!

**Comment by w0rp** [comment]
@jgehrig I've merged that PR now. I'll change one extra line to cover that in tests.
