### ISSUE TITLE
ALEGoToDefinition stop working

### ISSUE THREAD

**Issue by lesar** [dense-analysis/ale#3731]
## Information  

**VIM version**
VIM - Vi IMproved 8.2 (2019 Dec 12, compilato Apr 27 2021 18:57:19)                                                                                                    
Patch incluse: 1-2815                                                                                                                                                  

Operating System:  
Ubuntu 20.04.2 LTS
5.4.0-1035-raspi aarch64 

## What went wrong
I'm the author of [3536](https://github.com/dense-analysis/ale/issues/3536)  
after this I have work a lot of time and ale work very well.  
but now ALEGoToDefinition stop working: do not go to definition and not show error.  
I have update ALE but I do not know if is this the problem
I have update typescript too and have installed **typescript 4.2.4**

### :ALEInfo

 Current Filetype: javascript
Available Linters: ['eslint', 'fecs', 'flow', 'flow-language-server', 'jscs', 'jshint', 'standard', 'tsserver', 'xo']
  Enabled Linters: ['eslint', 'tsserver']
  Ignored Linters: []
 Suggested Fixers: 
  'eslint' - Apply eslint --fix to a file.
  'fecs' - Apply fecs format to a file.
  'importjs' - automatic imports for javascript
  'prettier' - Apply prettier to a file.
  'prettier_eslint', 'prettier-eslint' - Apply prettier-eslint to a file.
  'prettier_standard', 'prettier-standard' - Apply prettier-standard to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'standard' - Fix JavaScript files using standard --fix
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
  'xo' - Fix JavaScript/TypeScript files using xo --fix.
 Linter Variables:

let g:ale_javascript_eslint_executable = 'eslint'
let g:ale_javascript_eslint_options = ''
let g:ale_javascript_eslint_suppress_eslintignore = 0
let g:ale_javascript_eslint_suppress_missing_config = 0
let g:ale_javascript_eslint_use_global = 0
let g:ale_javascript_tsserver_config_path = ''
let g:ale_javascript_tsserver_executable = 'tsserver'
let g:ale_javascript_tsserver_use_global = 0
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'javascript': ['eslint', 'tsserver']}
let g:ale_linters_explicit = 1
let g:ale_linters_ignore = {}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = {'.*/node_modules/.*$': {'ale_enabled': 0}, '.*/dist/.*$': {'ale_enabled': 0}}
let g:ale_pattern_options_enabled = v:null
let g:ale_root = {}
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 1
let g:ale_sign_error = '>>'
let g:ale_sign_info = '--'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '--'
let g:ale_sign_warning = '--'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(finished - exit code 0) ['/bin/bash', '-c', 'cd ''/home/leonardo/sviluppo/www/project/node_modules/.pnpm/eslint@7.26.0'' && ''/home/leonardo/sviluppo/project/node_modules/.pnpm/eslint@7.26.0/node_modules/eslint/bin/eslint.js'' -f json --stdin --stdin-filename ''/home/leonardo/sviluppo/project/src/client/pages/home/HomeView.js'' < ''/tmp/vEYk9NQ/46/HomeView.js''']

<<<OUTPUT STARTS>>>
[{"filePath":"/home/leonardo/sviluppo/project/src/client/pages/home/HomeView.js","messages":[],"errorCount":0,"warningCount":0,"fixableErrorCount":0,"fixableWarningCount":0,"usedDeprecatedRules":[]}]
<<<OUTPUT ENDS>>>

(started) ['/bin/bash', '-c', '''/home/leonardo/sviluppo/project/node_modules/.bin/tsserver''']  

how can I do more check?  
someone have this problem too?  

best regards,  
Leonardo

**Comment by lesar** [comment]
I find this using channel.log file:  
```
Error: Cannot find module '/home/leonardo/sviluppo/www/project/node_modules/pnpm-global/5/node_modules/typescript/bin/tsserver'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
'
 12.897736 on 38: Dropping message 'internal/modules/cjs/loader.js:883
  throw err;
```
seams ALE is not finding tsserver.  
inside my project/node_module there is not pnpm-global folder at all.  
why ALE is searching for tsserver in wrong folder?

best regards,
Leonardo

**Comment by lesar** [comment]
Solved:
I think is a pnpm updating mistake.  
I have solved by:  

```bash
$ cd myproject
$ rm -r ./node_modules
$ rm pnpm-lock.yaml
$ pnpm install
```

and ALEGoToDefinition work again :-)

best regards,  
Leonardo
