### ISSUE TITLE
No Autocompletion for Elixir Files

### ISSUE THREAD

**Issue by LandonSchropp** [dense-analysis/ale#3816]
## Information

**VIM version**

NVIM v0.5.0
Build type: Release

Operating System: macOS 11.4

## What went wrong

For some reason, I can't seem to get ALE to auto-complete anything in Elixir files. This includes both elixir-ls autocompletion, as well as the standard language-agnostic word auto completion. I've tried running `:ALEInfo`, and nothing sticks out to me. I also made sure let `g:ale_completion_enabled = 1` was called first thing in my configuration files before anything was loaded. I made sure to enable all of the Elixir linters that were disabled by default.

My autocompletion works fine in other languages like JavaScript and Ruby. Language servers also seem to work fine in those languages.

## Reproducing the bug

Create a new empty Elixir file: `:tabe ~/Desktop/example.ex`. Then paste the following into the file:

``` elixir
defmodule Banana do
  def banana do
    "banana"
  end
end
```

At the end of this file, start typing the following:

```
IO.puts Banana.banana()
```

ALE should offer to autocomplete the module and filename, but nothing happens.

### :ALEInfo

```
 Current Filetype: elixir
Available Linters: ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']
  Enabled Linters: ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']
  Ignored Linters: []
 Suggested Fixers: 
  'mix_format' - Apply mix format to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_elixir_elixir_ls_config = {}
let g:ale_elixir_elixir_ls_release = '/usr/local/Cellar/elixir-ls'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'elixir': ['mix_format'], 'javascriptreact': ['eslint'], 'ruby': ['rubocop'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'elixir': ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {'javascriptreact': ['tsserver'], 'javascript': ['tsserver']}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '😦'
let g:ale_sign_info = '😡'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '😦'
let g:ale_sign_style_warning = '😡'
let g:ale_sign_warning = '😡'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) mix
(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Desktop/example.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/4/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' &&  mix help dialyzer && mix dialyzer < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/5/example.ex''']

<<<NO OUTPUT RETURNED>>>

(executable check - success) /usr/local/Cellar/elixir-ls/language_server.sh
(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Desktop/example.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/6/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' &&  mix help dialyzer && mix dialyzer < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/7/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Desktop/example.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/8/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' &&  mix help dialyzer && mix dialyzer < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/9/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Desktop/example.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/10/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' &&  mix help dialyzer && mix dialyzer < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/11/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Desktop/example.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/12/example.ex''']

<<<NO OUTPUT RETURNED>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''.'' &&  mix help dialyzer && mix dialyzer < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvimyUeVyq/13/example.ex''']

<<<NO OUTPUT RETURNED>>>

```

**Comment by LandonSchropp** [comment]
Well, now I feel dumb. Right after I submitted this issue, everything started working. Oh well. 🤷🏻‍♂️

**Comment by LandonSchropp** [comment]
Okay, I think I figured out where the issue is here. When I first start up Neovim, there's a period of about 30 seconds where the autocompletion needs to "warm up". During this time, my system's CPU spikes pretty high. I didn't catch this when I was testing before because I was rapidly restarting Neovim while I was configuring settings.

I'm not sure if this is an ALE problem or an elixir-ls problem. Please let me know if the issue is in elixir-ls, and I'll open an issue with them instead.

**Comment by LandonSchropp** [comment]
I've dug into this a bit more. When I first start the app and open an elixir file in my project, I get the output under ALE's command history:

```

 Current Filetype: elixir
Available Linters: ['credo', 'dialyxir', 'dogma', 'elixir-ls', 'mix']
  Enabled Linters: ['credo', 'elixir-ls', 'mix']
  Ignored Linters: []
 Suggested Fixers: 
  'mix_format' - Apply mix format to a file.
  'remove_trailing_lines' - Remove all blank lines at the end of a file.
  'trim_whitespace' - Remove all trailing whitespace characters at the end of every line.
 Linter Variables:

let g:ale_elixir_elixir_ls_config = {'elixirLS': {'dialyzerEnabled': v:false}}
let g:ale_elixir_elixir_ls_release = '/usr/local/Cellar/elixir-ls'
 Global Variables:

let g:ale_cache_executable_check_failures = v:null
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 0
let g:ale_completion_enabled = 1
let g:ale_completion_max_suggestions = 50
let g:ale_disable_lsp = 0
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'elixir': ['mix_format'], 'javascriptreact': ['eslint'], 'ruby': ['rubocop'], 'javascript': ['eslint']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_insert_leave = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'normal'
let g:ale_linter_aliases = {}
let g:ale_linters = {'elixir': ['credo', 'elixir-ls', 'mix']}
let g:ale_linters_explicit = 0
let g:ale_linters_ignore = {'javascriptreact': ['tsserver'], 'javascript': ['tsserver']}
let g:ale_list_vertical = 0
let g:ale_list_window_size = 10
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_lsp_root = {}
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = v:null
let g:ale_open_list = 0
let g:ale_pattern_options = v:null
let g:ale_pattern_options_enabled = v:null
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 1
let g:ale_set_quickfix = 0
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '😦'
let g:ale_sign_info = '😡'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '😦'
let g:ale_sign_style_warning = '😡'
let g:ale_sign_warning = '😡'
let g:ale_sign_highlight_linenrs = 0
let g:ale_statusline_format = v:null
let g:ale_type_map = {}
let g:ale_use_global_executables = v:null
let g:ale_virtualtext_cursor = 0
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) mix
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/3/lesson_controller.ex''']

<<<OUTPUT STARTS>>>

                                   mix credo

Run code analysis (use `--help` for options)

Location: _build/dev/lib/credo/ebin
<<<OUTPUT ENDS>>>

(executable check - success) /usr/local/Cellar/elixir-ls/language_server.sh
(started) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && MIX_BUILD_PATH=''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/4'' mix compile ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex''']
(started) ['/bin/zsh', '-c', '/usr/local/Cellar/elixir-ls/language_server.sh']
```

If I let it sit for a little while, and then look at the command history, I see the following:

```
  Command History:

(executable check - success) mix
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/3/lesson_controller.ex''']

<<<OUTPUT STARTS>>>

                                   mix credo

Run code analysis (use `--help` for options)

Location: _build/dev/lib/credo/ebin
<<<OUTPUT ENDS>>>

(executable check - success) /usr/local/Cellar/elixir-ls/language_server.sh
(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && MIX_BUILD_PATH=''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/4'' mix compile ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex''']

<<<OUTPUT STARTS>>>
==> remodel
Compiling 5 files (.ex)
Generated remodel app
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
==> zxcvbn
Compiling 8 files (.ex)
Generated zxcvbn app
==> bunt
Compiling 2 files (.ex)
Generated bunt app
===> Analyzing applications...
===> Compiling ranch
===> Analyzing applications...
===> Compiling telemetry
==> telemetry_metrics
Compiling 7 files (.ex)
Generated telemetry_metrics app
===> Analyzing applications...
===> Compiling telemetry_poller
==> decimal
Compiling 4 files (.ex)
Generated decimal app
==> jason
Compiling 8 files (.ex)
Generated jason app
==> sobelow
Compiling 51 files (.ex)
Generated sobelow app
==> comeonin
Compiling 4 files (.ex)
Generated comeonin app
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> argon2_elixir
mkdir -p /var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/4/lib/argon2_elixir/priv
cc -g -O3 -pthread -Wall -Wno-format-truncation -I"/usr/local/Cellar/erlang/24.0.3/lib/erlang/erts-12.0.3/include" -Iargon2/include -Iargon2/src -Ic_src -dynamiclib -undefined dynamic_lookup  argon2/src/argon2.c argon2/src/core.c argon2/src/blake2/blake2b.c argon2/src/thread.c argon2/src/encoding.c argon2/src/ref.c c_src/argon2_nif.c -o /var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/4/lib/argon2_elixir/priv/argon2_nif.so
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
Compiling 3 files (.ex)
Generated argon2_elixir app
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> credo
Compiling 214 files (.ex)
Generated credo app
==> ecto
Compiling 56 files (.ex)
Generated ecto app
==> phoenix_pubsub
Compiling 11 files (.ex)
Generated phoenix_pubsub app
===> Analyzing applications...
===> Compiling cowlib
===> Analyzing applications...
===> Compiling cowboy
===> Analyzing applications...
===> Compiling cowboy_telemetry
==> mime
Compiling 2 files (.ex)

== Compilation error in file lib/mime.ex ==
** (File.Error) could not stream "/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/4/lib/mime/priv/mime.types": no such file or directory
    (elixir 1.12.2) lib/file/stream.ex:83: anonymous fn/3 in Enumerable.File.Stream.reduce/3
    (elixir 1.12.2) lib/stream.ex:1517: anonymous fn/5 in Stream.resource/3
    (elixir 1.12.2) lib/enum.ex:3952: Enum.reduce/3
    lib/mime.ex:2: (module)
<<<OUTPUT ENDS>>>

(started) ['/bin/zsh', '-c', '/usr/local/Cellar/elixir-ls/language_server.sh']
```

It looks like ALE is compiling my entire app from scratch in a new directory, which would definitely explain the slow startup time. If I save my file and then wait until the CPU spike ends, I see the following:

```

(finished - exit code 0) ['/bin/zsh', '-c', '''mix'' format ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/15/lesson_controller.ex''']
(finished - exit code 0) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && mix help credo && mix credo suggest --format=flycheck --read-from-stdin ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex'' < ''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/16/lesson_controller.ex''']

<<<OUTPUT STARTS>>>

                                   mix credo

Run code analysis (use `--help` for options)

Location: _build/dev/lib/credo/ebin
<<<OUTPUT ENDS>>>

(finished - exit code 1) ['/bin/zsh', '-c', 'cd ''/Users/landon/Development/startup/chessercise_api'' && MIX_BUILD_PATH=''/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/17'' mix compile ''/Users/landon/Development/startup/chessercise_api/lib/chessercise_web/controllers/lesson_controller.ex''']

<<<OUTPUT STARTS>>>
==> remodel
Compiling 5 files (.ex)
Generated remodel app
==> file_system
Compiling 7 files (.ex)
Generated file_system app
==> connection
Compiling 1 file (.ex)
Generated connection app
==> zxcvbn
Compiling 8 files (.ex)
Generated zxcvbn app
==> bunt
Compiling 2 files (.ex)
Generated bunt app
===> Analyzing applications...
===> Compiling ranch
===> Analyzing applications...
===> Compiling telemetry
==> telemetry_metrics
Compiling 7 files (.ex)
Generated telemetry_metrics app
===> Analyzing applications...
===> Compiling telemetry_poller
==> decimal
Compiling 4 files (.ex)
Generated decimal app
==> jason
Compiling 8 files (.ex)
Generated jason app
==> sobelow
Compiling 51 files (.ex)
Generated sobelow app
==> comeonin
Compiling 4 files (.ex)
Generated comeonin app
==> elixir_make
Compiling 1 file (.ex)
Generated elixir_make app
==> argon2_elixir
mkdir -p /var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/17/lib/argon2_elixir/priv
cc -g -O3 -pthread -Wall -Wno-format-truncation -I"/usr/local/Cellar/erlang/24.0.3/lib/erlang/erts-12.0.3/include" -Iargon2/include -Iargon2/src -Ic_src -dynamiclib -undefined dynamic_lookup  argon2/src/argon2.c argon2/src/core.c argon2/src/blake2/blake2b.c argon2/src/thread.c argon2/src/encoding.c argon2/src/ref.c c_src/argon2_nif.c -o /var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/17/lib/argon2_elixir/priv/argon2_nif.so
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
warning: unknown warning option '-Wno-format-truncation' [-Wunknown-warning-option]
1 warning generated.
Compiling 3 files (.ex)
Generated argon2_elixir app
==> db_connection
Compiling 14 files (.ex)
Generated db_connection app
==> credo
Compiling 214 files (.ex)
Generated credo app
==> ecto
Compiling 56 files (.ex)
Generated ecto app
==> phoenix_pubsub
Compiling 11 files (.ex)
Generated phoenix_pubsub app
===> Analyzing applications...
===> Compiling cowlib
===> Analyzing applications...
===> Compiling cowboy
===> Analyzing applications...
===> Compiling cowboy_telemetry
==> mime
Compiling 2 files (.ex)

== Compilation error in file lib/mime.ex ==
** (File.Error) could not stream "/var/folders/mt/4fyz36kj69l0j5fffrwlsvdh0000gn/T/nvim7WHEb5/17/lib/mime/priv/mime.types": no such file or directory
    (elixir 1.12.2) lib/file/stream.ex:83: anonymous fn/3 in Enumerable.File.Stream.reduce/3
    (elixir 1.12.2) lib/stream.ex:1517: anonymous fn/5 in Stream.resource/3
    (elixir 1.12.2) lib/enum.ex:3952: Enum.reduce/3
    lib/mime.ex:2: (module)
<<<OUTPUT ENDS>>>
```

So I think the culprit here is that ALE recompiles the app from scratch on every save without any caching. I believe by default Elixir building everything into the local `_build` directory. Does ALE persist this directory in the folder it uses for compilation?

I believe this couple be what's causing some of the issues in #2397.
